on:
  push:
    branches:
      - main
      - patch/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app/build/outputs/apk/debug/app-debug.apk
